### ISSUE TITLE
Failed to parse invalid UTF8

### ISSUE THREAD

**Issue by amckinney** [jhump/protocompile-old#5]
The following comment cannot be parsed:

```protobuf
syntax = "proto2";

message Type {
  // An example of strange characters in a comment: attachment���s
  TYPE_UNSPECIFIED = 0;
}
```

I could write up a test case when I have a little more time, but thought I'd include the issue here for now.

**Comment by jhump** [comment]
What is the issue? Are you seeing an error or are you seeing something else? I would expect it to convert the invalid UTF8 characters to the [Unicode replacement character](https://www.fileformat.info/info/unicode/char/fffd/index.htm).

Also, FWIW, I think GitHub did the same to your example input above: it is valid UTF8 with the Unicode replacement character. In order to provide invalid UTF8 in a comment, you'd have to hex-encode it or upload it to a gist as a binary file.

I would prefer it to _fail_ on invalid input (and if we add a "strict mode", it definitely should). But `protoc` does not. On the other hand, `protoc` happily preserves invalid UTF8. I filed a bug for this several months ago: https://github.com/protocolbuffers/protobuf/issues/9175

**Comment by amckinney** [comment]
Yea, there's an error when trying to parse a file from [buf.build/googleapis/googleapis](https://buf.build/googleapis/googleapis) - [this](https://buf.build/googleapis/googleapis/file/main/google/cloud/compute/v1/compute.proto#L636) line in particular.

For example,

```sh
google/cloud/compute/v1/compute.proto:630:453: invalid UTF8 at offset 36302: ef
```

Presumably this works in `protoreflect` because we use it to parse the same file just fine.

> I would prefer it to fail on invalid input (and if we add a "strict mode", it definitely should)

I agree - it's a shame that this is even allowed in googleapis, but it'd be great if we could support this use case so that we can fully transition from `protoreflect` to `protocompile`.

I'm happy to discuss this more though - ideally we could get GoogleAPIs to remove that culprit line (it's the only case I've found so far), but I'm not sure how realistic that is.

**Comment by jhump** [comment]
This will be fixed in the new home for this repo (in `bufbuild`): https://github.com/bufbuild/protocompile/pull/34
